### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stevesbrain**
Minor grammar corrections

### CODE REVIEW

**Comment by franc-ist** [comment]
#hacktober

**Review by M1kep — APPROVED** [review]

**Comment by marzika** [comment]
I am currently not accepting PRs to the stable branch as it will be merged in the following days with the development one. Please clone the current development branch and submit the PR there. Thanks in advance!

**Comment by M1kep** [comment]
@stevesbrain , if you'd like to implement this in the dev branch that'd be great, if not I can just implement in my next pr

**Comment by stevesbrain** [comment]
Thanks @marzika - resubmitted in #299 (and thanks also @M1kep )

**Pull request closed without merging**
