### PR TITLE
Updated Saving system to 9.39.5

### PR DESCRIPTION
**Pull request by Andrerm124**
Should be fully comparable to previous versions

### CODE REVIEW

**Comment by JamesCaywood** [comment]
I can't get snapprefs to work with Snapchat 9.39.5 what am I doing wrong? It works for 9.31.

**Comment by M1kep** [comment]
@JamesCaywood are you building from source or downloading the jenkins dev build?

**Comment by JamesCaywood** [comment]
Downloading Jenkins I'm not smart to build haha

**Comment by M1kep** [comment]
@JamesCaywood Just be aware it is a DEVELOPMENT build

**Comment by Andrerm124** [comment]
@JamesCaywood You're gonna have to give me more details than that sorry. Why can't you get it to work? Are there any errors? Is it loading at all?

**Comment by JamesCaywood** [comment]
Oh well it didn't work for me?  Or I'm I post to delete snap perf then redownload  the whole thing?  BC I notice now when I went back to snapchat 9.31 now every time I save it tells them? But every thing is working? I'm confused

**Comment by Andrerm124** [comment]
@JamesCaywood I wouldn't advise using dev builds unless you're sure you know what you're doing. They're development builds that are usually in early stages and **do not generally work**

**Comment by JamesCaywood** [comment]
Oh alright I was just looking for snapperfs that work with a. Higher Snapchat ver BC 9.31 I get dang force closing and video lags when I take it and just annoying u know lol

**Pull request merged**
