### PR TITLE
Master

### PR DESCRIPTION
**Pull request by hbashton**
basically the same, but I updated a couple things to make it buildable and also updated obfuscated class names. I suggest you merge this to build with and update Obfuscator.java as you see fit. Thank you for your work, I'm just trying to help.

### CODE REVIEW

**Comment by marzika** [comment]
Hey!

I have reviewed your commits, which I am willing to accept, partly and not with merging it to my branch for the following reasons:
-Your commits contains the .idea and gen folders, which have no place on GitHub as they are generated each time a build is done or AS is opened
-Your commits would readd some files which have been already removed for a good reason, like Redeem.java and MainActivity2.java as they are no longer part of the app
-Your Obfuscator.java has to be manually reviewed, value by value, as I can already see errors like: L126, L192, L194.

**Comment by hbashton** [comment]
Can I send you my results for a profinder run?

**Comment by marzika** [comment]
Create a GitHub Gist and paste the link here.

**Comment by hbashton** [comment]
https://gist.github.com/hbashton/8d568c736d880857496d66387994d7e7

**Comment by AmineI** [comment]
Just compiled your version, and it's right that some classes aren't correctly replaced, the log shows that some of the classes names are missing in snapchat. You could try right now if you want, the Xposed log can help you with this.
Some bonus advices : I think it's a bad idea to edit project-specific values, like you did there with the MinSdkVersion . Since it's a pull request to a public github with collaborators, the main rule is that your contribution must be working for all the contributors and more : so the local properties, (with sdk local path etc) shouldn't be included, for example. Hope it helps you 😄

**Comment by hbashton** [comment]
I honestly just need someone to fix the obfuscator classes, and it will
work fine. I don't know any other way to do it

Just compiled your version, and it's right that some classes aren't
correctly replaced, the log shows that some of the classes names are
missing in snapchat. You could try right now if you want, the Xposed log
can help you with this.
- I think it's a bad idea to edit project-specific files, like the
  MinSdkVersion like you did there

**Pull request closed without merging**
