### PR TITLE
Update obfuscated class names to 9.28.2.0

### PR DESCRIPTION
**Pull request by teknogeek**

### CODE REVIEW

**Comment by hbashton** [comment]
does this add support for 9.28.2.0?

**Comment by NightMean** [comment]
Yes but there's already new version 9.29.1.0

**Comment by AmineI** [comment]
Mhh, @teknogeek why exactly did you remove apache dependency to replace it ? These are deprecated, right, but I personnally managed to compile it easily. I had to revert these modifications locally to compile the app without errors
+
Have you tried it actually ?

**Comment by turrets** [comment]
Tried compiling this, didn't work, had to add the apache dependency back for it to compile, and as soon as I did that and installed this version near enough none of the hooks worked.

**Comment by hbashton** [comment]
I compiled it, and if doesn't work with 9.28.2.0

**Comment by teknogeek** [comment]
i forgot to change some imports, that's why compiling doesnt work. i fixed it but havent pushed yet, noticed that some things arent working. note that this isn't just an instant update fix as things have changed....

**Comment by hbashton** [comment]
I managed to get it compiled, but it didn't work. does it work now?

**Comment by hbashton** [comment]
Question for all of you: how do you know what the new obfuscated classes are in the new Snapchat? surely we could automate the grab and push of these new classes

**Comment by AmineI** [comment]
Actually, finding the obfuscated classes is not complicated here. There are even tools that find them easily, like [Profinder](http://forum.xda-developers.com/android/software/profinder-proguard-obfuscation-tracker-t3183647)

**Comment by hbashton** [comment]
so in theory, decompiling a 9.28.2.0 and the most recent snapchat version and using profinder to find, and change, those classes would allow me to update it manually?

**Comment by AmineI** [comment]
Firstly it would be better checking from 9.21 to the last version. I'm not saying that teknogeek's work is unsure (I think what he did is correct but that the issue is linked to the second point of this comment), but a reference should be a working reference.
Secondly, since 9.21 Snapchat changed a lot, and they probably changed the code deeper so that just changing the obfuscations classes won't work.

**Pull request closed without merging**
